### ISSUE TITLE
Qnap Setup

### ISSUE THREAD

**Issue by myke2241** [rundqvist/docker-unmineable#1] opened 2021-09-07 15:56 UTC
I have had issues getting this working on qnap. Are there any guides for getting the miner running on Qnap?

**Comment by rundqvist** [comment] 2021-09-14 04:42
Hi,

Which architecture is it? And model?

**Comment by myke2241** [comment] 2021-09-14 20:35
Hello Mattias, thank for getting back to me. I am not a intel based Qnap TVS-1282. 

 

Here is what the terminal says. 

 

 

-- Configuration --

* CPU limited to to 200 (50 %)

* Difficulty set to: 7350 (if too many/few shares accepted, please set DIFFICULTY manually)

* Coin: ADA

* Wallet: 3Eybsvf4EPFTU8yDFDM2cxiUfuRyPxRoV5

* Worker: docker

* Donate: 1%

-- Starting miner --

/app/entrypoint.sh: line 55: xmrig: not found

Error: Invalid value for argument PID

Usage: cpulimit [OPTIONS...] TARGET

   OPTIONS

      -l, --limit=N          percentage of cpu allowed from 0 to 400 (required)

      -v, --verbose          show control statistics

      -z, --lazy             exit if there is no target process, or if it dies

      -i, --include-children limit also the children processes

      -h, --help             display this help and exit

   TARGET must be exactly one of these:

      -p, --pid=N            pid of the process (implies -z)

      -e, --exe=FILE         name of the executable program file or path name

      COMMAND [ARGS]         run this command and limit it (implies -z)

 

Report bugs to ***@***.***>.

 

From: Mattias Rundqvist ***@***.***>
Reply-To: rundqvist/docker-unmineable ***@***.***>
Date: Monday, September 13, 2021 at 9:42 PM
To: rundqvist/docker-unmineable ***@***.***>
Cc: myke2241 ***@***.***>, Author ***@***.***>
Subject: Re: [rundqvist/docker-unmineable] Qnap Setup (#1)

 

Hi,

Which architecture is it? And model?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rundqvist** [comment] 2021-09-15 17:11
Ok, thanks for the log. I'll look into it.

**Comment by rundqvist** [comment] 2021-09-18 20:01
I have pushed a new container image tagged as `:test`.

Please try it out with:
`docker run -d --name miner rundqvist/unmineable:test`
 and see if it solves the problem.

You also may have to run the container as privileged (if huge pages allocation fails).
`docker run -d --privileged --name miner rundqvist/unmineable:test`

**Comment by rundqvist** [comment] 2021-09-22 12:34
I have tested the `:test`-branch on my own setup and it works as intended, so I am now closing this issue and removing the `:test`-branch (code is promoted to `:latest`).
Please report back if you still experience problems.

**Closed as completed by rundqvist** 2021-09-22 12:34 UTC
